import React, { Suspense, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { Loader } from '@react-three/drei';
import Experience from './components/Experience';
import UIOverlay from './components/UIOverlay';

const App: React.FC = () => {
  // State to track if the house has been generated by the user
  const [houseGenerated, setHouseGenerated] = useState(false);

  return (
    <div className="relative w-full h-full bg-slate-900">
      <UIOverlay 
        onGenerate={() => setHouseGenerated(!houseGenerated)} 
        isGenerated={houseGenerated}
      />
      
      {/* 
        Canvas is the entry point to the Three.js scene.
        shadows: Enables shadow maps.
        camera: Sets initial position and field of view.
        dpr: Optimizes for device pixel ratio.
      */}
      <Canvas
        shadows
        camera={{ position: [8, 5, 8], fov: 45 }}
        dpr={[1, 2]}
        gl={{ preserveDrawingBuffer: true, antialias: true }}
        className="w-full h-full touch-none"
      >
        <Suspense fallback={null}>
          <Experience houseGenerated={houseGenerated} />
        </Suspense>
      </Canvas>
      
      {/* Loading indicator for any async assets/shaders */}
      <Loader />
    </div>
  );
};

export default App;