
export type ComponentType = 'floor' | 'wall' | 'roof' | 'door' | 'window' | 'generic';

export interface Vector3 {
  x: number;
  y: number;
  z: number;
}

// Low-level atomic part (Rendered by Three.js)
export interface ComponentConfig {
  id: string;
  type: ComponentType;
  position: Vector3;
  rotation?: Vector3;
  scale?: Vector3;
  size?: Vector3; // [width, height, depth]
  color?: string;
  material?: 'wood' | 'brick' | 'glass' | 'concrete' | 'metal' | 'stone' | 'roof_tiles';
  shape?: 'box' | 'cylinder' | 'prism' | 'pyramid'; 
  renderDelay?: number; // Runtime calculation
}

// High-level Architectural Module (Generated by AI)
export interface ModuleConfig {
  id: string;
  type: 'room' | 'tower';
  position: Vector3; // Center bottom position
  size: Vector3;     // [width, height, depth]
  style: {
    wallColor?: string;
    wallMaterial?: 'wood' | 'brick' | 'concrete' | 'stone';
    roofColor?: string;
    roofType?: 'flat' | 'gable' | 'pyramid' | 'cone';
    roofHeight?: number;
  };
}

export interface HouseBlueprint {
  id: string;
  name: string;
  // AI now generates 'modules', which we expand into 'components'
  modules: ModuleConfig[]; 
}